### ISSUE TITLE
SVLEN INFO field should be negative for deletions

### ISSUE THREAD

**Issue by waltergallegog** [cortes-ciriano-lab/savana#13]
Hello,
According to the vcf standard the svlen field should be negative for deletions:

 >Longer ALT alleles (e.g. insertions) have positive values, shorter ALT alleles (e.g.deletions) have negative values.

This conventions is also followed by other long read sv callers (cuteSV, nanomonsv).

As far as I can tell, savana's output has svlen positive for all types of svs. 

The correct svlen sign and the implementation of https://github.com/cortes-ciriano-lab/savana/issues/8 could help a lot with downstream analysis.

Thanks and BR.

**Comment by helrick** [comment]
Hi there, thanks for the suggestion! As I mention in #8, without copy number information, it's not possible to definitively call an SVTYPE (in [VCFv4.2](https://samtools.github.io/hts-specs/VCFv4.2.pdf)), so we use BND as the SVTYPE. GRIDSS has a more in depth explanation for their decision to do this here: https://github.com/PapenfussLab/gridss#why-are-all-calls-bnd. For the same reasons, it's not possible to determine whether an SVLEN should be positive or negative, so we've kept it positive for all SVs.

In future, we'll be moving to [VCFv4.4](https://samtools.github.io/hts-specs/VCFv4.4.pdf) in which the SVLEN value is required to always positive.

**Comment by waltergallegog** [comment]
Thanks for the detailed answer.
