### ISSUE TITLE
No records reported with tumor support lower than 6

### ISSUE THREAD

**Issue by waltergallegog** [cortes-ciriano-lab/savana#17]
Hello,
I have invoked savana using the `depth` parameter with value `2`. This is the full command:

```
 savana --tumour tumor.bam --normal normal.bam --ref ref.fa --outdir out/ --length 50 --depth 2 --threads 16 --debug >out.info 2>out.err
```
I'm using as savana output the file `somatic.sv_breakpoints.lenient.vcf`

Here are my observations after running Savana and nanomonsv on a tumor/normal pair:
 - Checking the vcf file produced by Savana, all obtained records have tumor supporting reads **6 or higher.**
 - All the Deletion SVs that are detected by NanomonSV and not by Savana (no breakends in the same position indicated by nanomonSV) have tumor supporting reads **5 or lower** as reported by NanomonSV.
 - Manually inspecting with IGV one of the deletions detected by NanomonSV and not Savana, with tumor supporting reads equal to 5, I can see evidence of the deletion in the long reads, supported by 5 reads. See the image. 
     - On the top the .bam file from the tumor sample. 
     - The deletion has length -79, and I have set Savana `--length` parameter to `50`. Other Deletions of similar length are identified by Savana)
     - MAPQ of the 5 reads is 60.

This makes me think that perhaps the `--depth` parameter is not working correctly, and is set to `6`.
Let me know what other files of the Savana output I can check to understand what could explain this behavior.

Thanks and Best regards.

![image](https://user-images.githubusercontent.com/5270762/222222119-1132e7e2-2c2b-4fa2-b72a-c1ee0befa24a.png)

**Comment by helrick** [comment]
Thanks for raising this issue. Yes, you are correct in that the depth value is not being used correctly by SAVANA. This value is actually used internally by the algorithm and doesn't make sense as a parameter. I've removed it in the working branch for the next release of SAVANA.

I'm currently working on improving variant filtering for SAVANA and hope to have a new release shortly which will allow users to set custom filters on fields such as support.

In the meantime, does this variant appear in the `{sample}.sv_breakpoints.vcf` file? This VCF contains all variants before filtering and can be custom filtered for depth using the `TUMOUR_SUPPORT` and `NORMAL_SUPPORT` fields in the `INFO` field.

**Comment by waltergallegog** [comment]
In the meantime I would like to do some custom filtering using the `bcftools view -i` command.
Just to confirm, the current filtering for the `lenient` version is done by the following function correct?
```python
def apply_somatic_filters(validated_breakpoints):
	""" use heuristics to eliminate noise and germline variants """
	somatic_breakpoints_lenient = []
	for bp in validated_breakpoints:
		if bp.support['tumour'] == 0:
			continue
		elif bp.support['normal']/bp.support['tumour'] < 0.1:
			originating_cluster_stats = bp.originating_cluster.get_stats()
			end_cluster_stats = bp.end_cluster.get_stats()
			if originating_cluster_stats['starts_std_dev'] < 150 and originating_cluster_stats['event_heuristic'] < 3:
				if bp.breakpoint_notation == "<INS>" and bp.support['tumour'] > 25:
					somatic_breakpoints_lenient.append(bp)
				elif bp.breakpoint_notation != "<INS>" and bp.support['tumour'] > 5:
					somatic_breakpoints_lenient.append(bp)
```

If that is the correct function, I have prepared the following bcftools command that seems to produce the same results, and that I will customize to my needs.

```
bcftools view -i 
'
TUMOUR_SUPPORT>0 
& (NORMAL_SUPPORT/TUMOUR_SUPPORT)<0.099 
& ORIGIN_STARTS_STD_DEV<150
& ORIGIN_EVENT_HEURISTIC<3 
& ((BP_NOTATION=="<INS>" & TUMOUR_SUPPORT>25) | (BP_NOTATION!="<INS>" & TUMOUR_SUPPORT>5))
' 
sv_breakpoints.vcf > somatic.sv_breakpoints.lenient.bcftools.vc
```

**Comment by helrick** [comment]
Hi Walter, apologies for the delay in response. That is indeed the part of the code that applies the filters. I can't comment on the `bcftools` command as I haven't tested it, but from a quick glance it looks correct.

I've just released a newer version of SAVANA which should address the issue you raised and also provide the ability to custom filter your variants using a `JSON` file. The above method using `bcftools` should still work when applied on the raw `sv_breakpoints.vcf` file if you want to include more complex logic in your filters.

**Comment by waltergallegog** [comment]
Hi Hillary, thanks for the new release and the ability to use filters with the json file.

I tried to use the above `bcftools` command on the  raw `sv_breakpints.vcf` file but I get an error as bcftools can not find the field `ORIGIN_EVENT_HEURISTIC`.

Has the name of the field changed, or has it been removed? Should I remove it from the command?

**Comment by helrick** [comment]
Hi there, apologies I missed your final question on this thread, but I can confirm that the field `ORIGIN_EVENT_HEURISTIC` has been removed yes.
