### ISSUE TITLE
No read depth

### ISSUE THREAD

**Issue by Akazhiel** [cortes-ciriano-lab/savana#19]
Hello,

First of all great tool, been craving for a somatic caller for long-read data since NanomonSV didn't work too well. I just wanted to ask if there are any plans to report read depth for the breakpoints detected? I've seen the tool applies filters based on evidence supporting reads but we'd like to filter some events based on VAF and would need the read depth where the event takes place to compute it.

Best regards,

Jonatan

**Comment by helrick** [comment]
Hello,

Thank you for your issue. Glad to hear that SAVANA has been working for you! Yes the read depth is planned to be reported. It's currently implemented in [Draft PR #15](https://github.com/cortes-ciriano-lab/savana/pull/15) which should be merged soon for version 0.3.x of SAVANA. It will be reported as `TUMOUR_DP=n,m` and `NORMAL_DP=n,m` in the VCF file, which corresponds to the number of reads at each edge of the breakpoint location in the tumour and normal bam files respectively (the other line in the VCF corresponding to the other breakpoint will be flipped, i.e.) `TUMOUR_DP=m,n`)

Let me know if this will work for your use case or if any modifications would make your task easier.

Many thanks,
Hillary
