### ISSUE TITLE
might it work on a Mac?

### ISSUE THREAD

**Issue by proukakis** [cortes-ciriano-lab/savana#36]
Hello, the conda doesn't seem to have a Mac version, do you know if it has ever been tested on Mac? thanks

**Comment by helrick** [comment]
Hi there, I haven't tested SAVANA on a Mac before but in theory it should work if you follow the instructions to install from source. However, I caution that the memory and time requirements of SAVANA make it better suited to be run in an HPC environment, especially if you are using genomic data with coverage > 15x.
