### ISSUE TITLE
Unavailibility of normal tissue sample

### ISSUE THREAD

**Issue by sachingadakh** [cortes-ciriano-lab/savana#42]
Hello 
I have tumor sample data, which we sequenced using RRMS adaptive sampling, but due to certain reasons, we don't have data on the normal tissue of the same individual. Therefore, this may sound naive question, but I want to ask, can I use GM12878 as a normal sample to call SVs and CNAs.
Any kind of insights will be helpful in this issue.
Thank you

**Comment by cmsauer** [comment]
Hi there, 
Difficult to comment on this, as we do not recommend performing SV analysis without a matched normal sample, and you do indeed need to provide a normal sample to run savana. 
Also, as a side note, what is the genome-wide coverage and read length for the RRMS adaptive sampling data that you are trying to analyse? In general we recommend whole-genome long-read data. 
Either way, you are able to run the CNA part (savana cna) without a normal sample provided. The sample will be self-normalised instead for the copy number analysis. But do note that if you do not have a matched normal, you will not be able to generate minor allele copy number data or accurately estimate the purity and ploidy of the sample, in addition to of course not being able to perform SV calling. 
Hope this helps!
