### ISSUE TITLE
--cn_binsize is a required argument for the main/default savana process

### ISSUE THREAD

**Issue by TBradley27** [cortes-ciriano-lab/savana#43]
Hello,

Firstly, congrats to the Cortes Ciriano team for getting v1.2.0 and the preprint released! I am looking forward to using.

I am just writing about the following minor issue:

`--cn_binsize` is listed as not being a required argument for the CNA subcommand:

https://github.com/cortes-ciriano-lab/savana/blob/9cea04122a31136f47a6f128c419555b8f62e6e8/savana/savana.py#L353

However, it is listed as a required argument for the main savana process:

https://github.com/cortes-ciriano-lab/savana/blob/9cea04122a31136f47a6f128c419555b8f62e6e8/savana/savana.py#L448

It is also not listed as a required argument in the README:

https://github.com/cortes-ciriano-lab/savana/blob/9cea04122a31136f47a6f128c419555b8f62e6e8/README.md?plain=1#L104-L106

**Comment by cmsauer** [comment]
Hi Thomas, 
Good catch, thank you for spotting and reporting this, will fix!
Carolin
