### ISSUE TITLE
savana run error

### ISSUE THREAD

**Issue by andyjslee** [cortes-ciriano-lab/savana#50]
I got the following error when running `savana run` on savana v1.2.3:

`savana.py line 48 in savana_run: AttributeError: 'Namespace' object has no attribute 'cna_threads'`

I think the `run` CLI either doesn't need the `cna_threads` argument or is missing the declaration in the arg parser?

**Comment by helrick** [comment]
Hi there, thanks for raising this! I've fixed this bug in 52e450ff6afa8692b8a0ca214bc269b821789693 - it should be resolved in the most recent release ([v1.2.4](https://github.com/cortes-ciriano-lab/savana/releases/tag/1.2.4))
