### ISSUE TITLE
help with calling somatic SVs with savana 1.2.4

### ISSUE THREAD

**Issue by apsteinberg** [cortes-ciriano-lab/savana#53]
Hi there,

Thanks again for building this great tool. I have been trying to call somatic SVs with savana 1.2.4 on a rhabdoid tumor, where I am expecting there to be somewhere between 10-20 somatic SVs. This is also what I am finding from other SV callers. However, for some reason when I run savana on this sample, I am finding that there are 1000s of SVs. I am wondering if the way I am implementing savana is flawed? This is what my script looks like (I've edited paths to remove anything that could be PHI):

```
singularity run --bind /data1/shahs3:/data1/shahs3 /data1/shahs3/users/preskaa/singularity/savana_1.2.4--pyhdfd78af_0.sif savana run --tumour tumor.bam --normal normal.bam --outdir /data1/shahs3/isabl_data_lake/analyses/43/70/44370 --ref /data1/shahs3/reference/ref-sarcoma/GRCh38/v45/GRCh38.primary_assembly.genome.fa --contigs /data1/shahs3/reference/ref-sarcoma/GRCh38/v45/contigs.chr.hg38.txt --threads 8 --min_af 0.05

singularity run --bind /data1/shahs3:/data1/shahs3 /data1/shahs3/users/preskaa/singularity/savana_1.2.4--pyhdfd78af_0.sif savana classify --vcf tumor.sorted.sv_breakpoints.vcf --custom_params /data1/shahs3/isabl_data_lake/analyses/43/70/44370/classification-parameters.json --output tumor.classified.vcf --min_af 0.05 --threads 8
```
The classification-parameters.json looks like this:

```
{
    "somatic": {
        "MAX_NORMAL_READ_SUPPORT": 0
    }
}
```
The singularity image I used was pulled from here: https://quay.io/repository/biocontainers/savana?tab=info 

Happy to provide any additional information that may be useful.

Thanks for your time and help.

Best,
Asher

**Comment by helrick** [comment]
Hi there! Thanks for raising this issue, happy to clarify :)

Was this sample sequenced with nanopore or PacBio? If nanopore, I'd recommend using the trained model to perform the classification:
```
singularity run --bind /data1/shahs3:/data1/shahs3 /data1/shahs3/users/preskaa/singularity/savana_1.2.4--pyhdfd78af_0.sif savana classify --vcf tumor.sorted.sv_breakpoints.vcf --ont --output tumor.classified.vcf --min_af 0.05 --threads 8
```
and if PacBio, the same command but swapping out `--ont` for `--pb` which will implement a set of filters [that can be found here](https://github.com/cortes-ciriano-lab/savana/tree/main?tab=readme-ov-file#classify-for-pacbio).

Regardless of whether the SVs were classified as somatic or not, they will be in the `tumor.classified.vcf`, so you'll need to filter for "PASS" SVs to ensure only SVs classified as somatic are present. Alternately, you can provide another argument to the `savana classify` command: `--somatic tumor.classified.somatic.vcf` and the `tumor.classified.somatic.vcf` will contain only somatic SVs.

If you'd prefer to use a custom classification JSON file, I'd recommend adding more filtering parameters. The custom JSON you provided will only remove SVs if they have normal support. However, there are many other variables that should be considered. If you go this route, I'd recommend doing some trial and error to see which filters work best for your data.

For example, you may want to include a minimum threshold on the required number of tumour reads via "MIN_TUMOUR_READ_SUPPORT" and the maximum number of normal reads with evidence of an SV (of any type) clustering to that the location via "MAX_CLUSTERED_READS_NORMAL". Additionally, there are other thresholds such as "MAX_ORIGIN_STARTS_STD_DEV" and "MAX_ORIGIN_EVENT_SIZE_STD_DEV" which are related to the standard deviation of the position and size of an SV and can be used to distinguish between noise and true somatic SVs. You can find more information about some of these fields [here](https://github.com/cortes-ciriano-lab/savana/tree/main?tab=readme-ov-file#classify-by-parameters-file).

Let me know if you have any more questions or run into issues with the above.

All the best,
Hillary

**Comment by apsteinberg** [comment]
Hi Hillary,

Thanks for the quick and comprehensive reply, this was super helpful! I was able to successfully run savana with your suggestions here, and the somatic SV counts is much more in line with what I anticipated. As a follow-up question, I was wondering if it is possible to use both the `--ont` flag and the `--custom_params` flag together?

Thanks again for your time and help.

Best,
Asher

**Comment by helrick** [comment]
Hi Asher,

Glad I was able to help! In combination with the `--ont` flag you can also apply a threshold to the minimum number of supporting tumour reads (using `--min_support`) and a minimum tumour allele-fraction (using `--min_af`).

If you wanted to apply more detailed custom filters than support and AF though, you could use the `somatic` VCF from a classify command run using the `--ont` flag and run it through another classification round using a custom JSON.

For example, to apply the model:

```
singularity run --bind /data1/shahs3:/data1/shahs3 /data1/shahs3/users/preskaa/singularity/savana_1.2.4--pyhdfd78af_0.sif savana classify --vcf tumor.sorted.sv_breakpoints.vcf --ont --output tumor.classified.vcf --threads 8 --somatic tumor.classified.somatic.vcf
```
and then, to filter the somatic calls even further with a custom JSON:
```
singularity run --bind /data1/shahs3:/data1/shahs3 /data1/shahs3/users/preskaa/singularity/savana_1.2.4--pyhdfd78af_0.sif savana classify --vcf somatic tumor.classified.somatic.vcf --custom_json classification-parameters.json --output tumor.classified.somatic.custom_filters.vcf
```

However, neither of these methods would recover calls that met the custom thresholds but were not classified as somatic by the model, they would only further filter the model's calls.

All the best,
Hillary

**Comment by apsteinberg** [comment]
Hi Hillary,

Sorry I forgot to respond to this -- thank you for the detailed response here! This is very helpful. I tried the first option you mentioned (`--ont` flag with the `--min_af` flag and it worked great). I have yet to try filtering the somatic calls further with the custom json but this looks like it will be very useful as well.

Thanks again and best wishes,
Asher
