### ISSUE TITLE
copy number fitting error

### ISSUE THREAD

**Issue by apsteinberg** [cortes-ciriano-lab/savana#56]
Hi there,

Thank you again for building this great tool. We are starting to explore the copy number analysis function in our group, and we are finding that it is working on most of our samples, but one of the samples is giving us the following error (this is the end of the log file):

```
Performed CBS                                               55.106 seconds
... CN fitting will use threads = 8. (threads = 8 defined; threads = 64 available) ...
     ... Allele counts for phased hetSNPs provided and being processed to estimate sample purity ...
        estimated cellularity using hetSNPs = 0.92.
Fit of purity=1.0 and ploidy=2.98 is NOT an acceptable solution, as main CN change step = 2.
No fits found. See No_fit_found_PARAMS_out.tsv in output
```
The command we ran was:

```
singularity run --bind /data1/shahs3:/data1/shahs3 /data1/shahs3/users/preskaa/singularity/savana_1.2.4--pyhdfd78af_0.sif savana cna --tumour /data1/shahs3/isabl_data_lake/analyses/21/72/42172/results/minimap2/SHAH_H003458_T01_01_WG01_R1.sorted.bam --normal /data1/shahs3/isabl_data_lake/analyses/21/92/42192/results/minimap2/SHAH_H003458_N01_01_WG01_R1.sorted.bam --outdir /data1/shahs3/isabl_data_lake/analyses/45/50/44550/results --ref /data1/shahs3/reference/ref-sarcoma/GRCh38/v45/GRCh38.primary_assembly.genome.fa --phased_vcf /data1/shahs3/isabl_data_lake/analyses/45/40/44540/SHAH_H003458_N01_01_WG01_phased.vcf --breakpoints /data1/shahs3/isabl_data_lake/analyses/44/89/44489/results/somatic_SVs/SHAH_H003458_T01_01_WG01_filtered_ensemble.vcf --sample SHAH_H003458_T01_01_WG01 --cna_threads 8 --chromosomes 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 --no_blacklist
```
Is there any parameters you would suggest switching to remedy this? I've also attached the full log in case it is useful:
[head_job.log](https://github.com/user-attachments/files/17905692/head_job.log)

Another question we had is if there is a recommended set of black list regions you would suggest using for hg38? We are working with ONT data here, if this is helpful.

Thanks a bunch for your time and help.

Best,
Asher

**Comment by cmsauer** [comment]
Hi Asher, 
Pleased to hear you are using and exploring the copy number feature of Savana and that it works well for you. 
The error message indicates that the purity-ploidy fit found for this sample might not be as optimal or as good of a fit as we would like it to be, which means we have less confidence on this being the correct fit. As such the tool puts out the error message you see above. It's actually not an error message indicating that the CN analysis part did not work, just that no fit was found fulfilling all the stringent criteria we impose. 
If you would like to fit this sample anyway, and just inspect the resulting CN data and CN profile carefully, you can consider using `--main_cn_step_change 2` (the default is 1). This would allow the above solution to be selected for copy number fitting and estimation. 

Regarding your blacklisting question, we are currently working on understanding which blacklist might be most appropriate for this, but I think you would be safe to use a standard hg38 blacklist, or manually curate one, if for example, you wanted to exclude telomeric and centromeric regions from the CN analysis. The code already takes care of missing bases and excludes bins where the majority of bases in the reference are unknown. 

I hope this helps!
Carolin

**Comment by apsteinberg** [comment]
Hi Carolin,

I realize I forgot to reply here -- thanks for your advice, this is really helpful and I will take the steps you've suggested.

Best,
Asher
